use serde::{Deserialize, Serialize};


#[derive(Serialize, Deserialize)]
pub enum StatusTypes{
    LOG_IN_SUCCESSFUL,
    REGISTRATION_SUCCESSFUL,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    TOKEN_GRANTED,
    ROOM_CREATION_SUCCESSFUL,
    ROOM_AUTHORIZATION_SUCCESSFUL,
    ROOM_NOT_FOUND,
    ROOM_FOUND,
    ADD_REQUEST_SENT,
    USER_ADDED,
    USER_IGNORED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    AUTHORIZED,
    DATABASE_ERROR,
    NOTIFICATIONS_ERROR,
    NOTIFICATIONS_FETCHED_SUCCESSFULLY,
    DMS_DATA_FETCHED,
    DMS_DATA_UPLOADED,
    USER_ALREADY_EXISTS,
    ROOM_ALREADY_EXISTS,
    USER_ALREADY_BLOCKED
}