#[derive(Debug, Clone)]
pub enum Screens {
    WELCOME_SCREEN,
    REGISTER_SCREEN,
    LOGIN_SCREEN,
    CHAT_OPTIONS_SCREEN,
    PUBLIC_CHAT_SCREEN,
    ROOM_CREATION_SCREEN,
    ROOM_JOIN_SCREEN,
    ROOM_CHAT_SCREEN,
    ADD_USER_SCREEN,
    DM_USER_SCREEN,
    DM_CHAT_SCREEN,
    BLOCK_USER_SCREEN,
    NOTIFICATIONS_SCREEN
}
